!
!     Constant parameter definition
!
      INTEGER            IPINST
!                              , KMAX1,  KMAX2,  KMAX3, NATO
!      INTEGER            NCOM, NDIF, NRAD, NSYM, NWAV
      INTEGER            NRAD, NSYM
      DOUBLE PRECISION   PI
      PARAMETER (IPINST= 190)
!      PARAMETER          (KMAX1=   42)
!      PARAMETER          (KMAX2=   82)
!      PARAMETER          (KMAX3=   100)
!      PARAMETER          (NATO=   18)
!     ncom=121 corresponds to LMAX2=10
      PARAMETER (NCOM=   121)                   
!      PARAMETER          (NDIF=   64)
      PARAMETER (NRAD=  881)                                              
      PARAMETER (NSYM=   48) 
!      PARAMETER          (NWAV=   40000)
      PARAMETER (PI=3.14159265358979323846264338327950d0)
!      PARAMETER          (LMAX2=   8)
