!
!     Constant parameter definition
!
      INTEGER            LMAX1D, NCOM, NRAD, NSTD, NSPD, LMAX2
      PARAMETER          (LMAX2=   8)
      PARAMETER (LMAX1D=  LMAX2+1)
!      PARAMETER (LMAX1D=  9)
!      PARAMETER          (NATO=   48)
      PARAMETER (NCOM=   121)                                              
!      PARAMETER          (NDIF=   64)
      PARAMETER (NRAD=  881)                                              
      PARAMETER (NSTD=   30)
      PARAMETER (NSPD=2*LMAX1D*LMAX1D-LMAX1D+NSTD)
!      PARAMETER (NSYM=   48)                                              
!      PARAMETER          (NWAV=   40000)

