#!/bin/csh -f
# expand all WIEN97 tar files
#
set name  = $0
set bin   = $name:h             

if !($#argv == 0) then
    if ($1 == -h || $1 == -H) then
	echo "expand_lapw" expands all WIEN tar-files in the current subdir"
	exit(1)
    endif	
endif

#
echo "WARNING: This will expand all WIEN.tar files \!\!\!"
echo "It will overwrite all changes you have made previously in the WIEN subdirectories"
echo "continue (y/n) "
set b=($<)
if ($b == 'y') then 
   foreach i ( SRC*.tar TiC.tar fccni.tar TiO2.tar example_struct_files.tar )
   
    if (-e $i) then
	echo "tar -xf $i"
	tar -xf $i
    endif
   end


cp SRC/VERSION .

foreach i ( SRC/*_lapw )
	  if (-e $i) then
	    cp $i .
            set fn = `echo $i:t |sed "s/_lapw//"`
            if (-e $fn) rm $fn
            ln -s $i:t $fn
            echo "$i   copied and linked to   $fn"
	  else
	    echo "$i not found\!"
	  endif  
end

#if ( -e wien ) rm wien
#    ln -s SRC_wienbox/wien wien

if ( -e w2web ) rm w2web
    ln -s SRC_w2web/w2web w2web
if ( -e SRC_w2web/htdocs/usersguide) then
     rm -r SRC_w2web/htdocs/usersguide
endif
    ln -s $PWD/SRC_usersguide_html SRC_w2web/htdocs/usersguide
    cd $PWD/SRC_usersguide_html
    ln -s ../SRC/usersguide.pdf .
    cd ..

foreach i (lapw1 lapw2 lapwso optic  lapwdm  )
    if (-e ${i}cpara ) rm ${i}cpara
    ln -s ${i}para ${i}cpara
end

cd SRC_structeditor
ln -s ../SRC_lib .
cd ..

if(-e INSTALLDATE) rm INSTALLDATE

chmod +x siteconfig_lapw

cat<<EOF

WIEN is now expanded. The shell-script commands were copied and links created.
To configure your Fortran-executables run:

./siteconfig_lapw


EOF

endif

exit(0)




