#!/bin/csh -f
#
# (C)1997 by Joachim Luitz
#
# $Revision: 1.3 $
# $Date: 1997/12/02 13:00:22 $
#
# $Author: jluitz $
# $Source: /zeus/lapw/WIEN97/bin/RCS/testpara2_lapw,v $
# $State: Exp $
#
unalias rm

if !(-e .machines) then
    echo "Case not set up for parallel execution\!"
    echo "No .machines file present."
    exit 1
endif

set tmp = .tmp_testpara2.$$
onintr exit

alias   testinput       'if (! -e \!:1 || -z \!:1) goto \!:2'
alias   testerror       'if (! -z \!:1.error) goto error'







############################################################################
#In this section use 0 to turn of an option, 1 to turn it on, 
#respectively choose a value

set debug       = 0             # verbosity of debugging output

############################################################################

if !(-e .processes2) then
    set jdone = 0
    set junks = 1
    goto show
endif
set line = `head -1 .processes2`
set jdone = `echo $line|cut -f1 -d:`
set junks = `echo $line|cut -f2 -d:`

show:
set percent = `echo "$jdone * 100 / $junks" | bc`

echo ""
echo "#####################################################"
echo "#                     TESTPARA2                     #"
echo "#####################################################"
echo ""
date
echo ""
if !(-e .lapw2para) then
    echo "   lapw2para was not yet executed"
    exit
endif

set test = `cat .lapw2para`

if ($test == "DONE") then
    echo "    lapw2para has finished"
    exit
endif

if ($test == "ERROR") then
    echo "    lapw2para exited due to an ERROR"
    echo "    Check *.error files"
    exit
endif

echo "     lapw2para is running"
echo ""
echo "$jdone of $junks ($percent%) junks distributed"
echo ""
echo "machines(processors) in calling order are:"
tail -1 .processes2 |  awk '{ for (i = 1 ; i <= NF; i += 4) {j=i+1;k=i+2;l=i+3;print "\t" $i "\t" $j "\t" $k "\t" $l} }'

exit
set machines = `grep init: .processes|cut -f2 -d:|xargs`

exit:
    rm $tmp* >&/dev/null
