SHELL = /bin/sh
FC = ifort
FOPT =  -FR -mp1 -prec_div -r8 -pc80 -fpconstant -traceback -pad -align -O3 -ipo1 -DINTEL_VML -i-static -fminshared -axNP
LDFLAGS = $(FOPT) -L/opt2/intel/fc/9.0/lib -L/opt2/intel/mkl/8.0.1/lib/32
R_LIBS = -lsvml -lmkl_lapack -lmkl_ia32 -lguide -lpthread
DESTDIR = ./
EXECNAME = pairhess
EXECN2 = patchsymm
###############################################################################
###############################################################################

EXEC   = $(DESTDIR)$(EXECNAME)
EXEC2  = $(DESTDIR)$(EXECN2)
EXEC3  = $(DESTDIR)$(EXECN3)
#..............................................................................
#
#  All object files, including $(SP_OBJS) and $(OBJSMOD) 
#
OBJS  = energy.o findneigh.o findsymm.o fixup.o gen_brav.o init.o main.o makehess.o sortag.o \
        pickneigh.o dchdc.o  errclr.o errflg.o gtfnam.o outerr.o expandset.o makehessb.o \
        outerr.o errclr.o  findequivs.o matcon.o
OBJ2  = patch.o fixup.o gtfnam.o
#..............................................................................

$(EXEC): $(OBJS) $(OBJ2) $(OBJ3)
	$(FC) -o $(EXEC) $(OBJS) $(LDFLAGS) $(R_LIBS)
	$(FC) -o $(EXEC2) $(OBJ2) $(LDFLAGS) $(R_LIBS)
#..............................................................................
#
#  All routines depend upon an include file (contains common PARAMETERS)

$(OBJS): Makefile params.inc

#..............................................................................
#  remove unnecessary files 
clean:
	rm -f *.o
#..............................................................................
#
#  define inference rules to generate object files from source files
#
.f.o:
	$(FC) $(FOPT) -c $<
