      SUBROUTINE OPNFS(DEFFN,ERRFN,FL)
      IMPLICIT REAL*8(A-H,O-Z)
      PARAMETER (iFLMAX=    3) 
!
      CHARACTER*80    DEFFN,ERRFN,FNAME
      CHARACTER*11    STATUS,FORM
      LOGICAL         FL(3)
!**********************************************************************
!
      DO 5 II=1,iFLMAX
 5       FL(II)=.FALSE.
      CALL GTFNAM(DEFFN,ERRFN)
      OPEN(1,FILE=DEFFN,STATUS='OLD',ERR=8000)
 8003 READ(1,*,END=8001) IUNIT,FNAME,STATUS,FORM,IRECL
      OPEN(IUNIT,FILE=FNAME,STATUS=STATUS,FORM=FORM,ERR=8002)
      GOTO 8003
 8000 WRITE(*,*) ' ERROR IN OPENING LDA+U.DEF !!!!'
      STOP 'ORB.DEF'
 8002 WRITE(*,*) ' ERROR IN OPENING UNIT:',IUNIT
      WRITE(*,*) '       FILENAME: ',FNAME,'  STATUS: ',STATUS, &
      '  FORM:',FORM
      STOP 'OPEN FAILED'
 8001 CONTINUE
      CLOSE (1)
!
      END  
