!
!     Constant parameter definition
!     RMAX0:  max. distance for atomic radial mesh
!
      INTEGER   NPT,NPT00
      PARAMETER (RMAX0= 16.d0)                                              
      PARAMETER (NPT= 981)                                              
      PARAMETER (NPT00= 190)                                              
!     note: NPT=NRAD+NPT00                                              

