FC = _FC_
FOPT     = _FOPT_
FGEN     = 
LDFLAGS  = _LDFLAGS_
DESTDIR  = ./
EXECNAME = eosfit

EXEC   = $(DESTDIR)$(EXECNAME)

OBJS =	eosfit.o gtfnam.o lmdif.o

$(EXEC):	$(OBJS)
	$(FC) -o $(EXEC) $(OBJS) $(FOPT) $(LDFLAGS) 

$(OBJS):	Makefile

clean:	  
	-rm eosfit *.o
	@echo clean

.f.o:
	$(FC) $(FOPT) -c $<	
.f90.o:
	$(FC) $(FOPT) -c $<
