#!/bin/csh -f
#extract data from scf file
#variables: $1 item to grep for
#           $2 name of file
#           $3 lines for tail

# $Revision: 1.1 $
# $Date: 1997/01/31 07:34:12 $
#
# $Author: jluitz $
# $Source: /planck/lapw/RCS/getdata,v $
# $State: Exp $
unalias rm


if ($#argv != 3) then
   echo 'syntax:         getdata string filename lines_for_tail '
   exit(1)
endif

set count = `grep $1 $2|wc`
if ( $count[1] == "0" ) then
	echo "$1  : no entry"
else
	grep $1 $2 |tail -$3
endif
